import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import RegisterDialog from "./(web)/_components/auth/RegisterDialog";



export const metadata: Metadata = {
  title: "Care rental",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-[#EBF2F7] antialiased`}>
          <RegisterDialog />
          {children}
          <Toaster />
      </body>
    </html>
  );
}
